# syntax=docker/dockerfile:1

############################
# 1) deps (instala todo)
############################
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci

############################
# 2) build
############################
FROM node:20-alpine AS build
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

############################
# 3) runner (solo prod deps)
############################
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/dist ./dist

# Railway usa la variable PORT
EXPOSE 3000
CMD ["node", "dist/main.js"]
